#!/usr/bin/env python3
"""Generate sh.py, ctypes bindings, from scripthook.h.

Run at build time: python3 gen_sh.py scripthook.h ../python/sh.py
Every SH_API function becomes sh.<Name> minus the Sh prefix,
and every simple typedef struct becomes a ctypes.Structure.
"""
import re
import sys

CTYPE = {
    "void": None,
    "int": "c_int",
    "float": "c_float",
    "double": "c_double",
    "char": "c_char",
    "uint8_t": "c_uint8",
    "uint16_t": "c_uint16",
    "uint32_t": "c_uint32",
    "uint64_t": "c_uint64",
    "int8_t": "c_int8",
    "int16_t": "c_int16",
    "int32_t": "c_int32",
    "int64_t": "c_int64",
    "size_t": "c_size_t",
    "uintptr_t": "c_uint64",
}


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    return re.sub(r"//[^\n]*", " ", text)


def ctype_of(decl, structs):
    decl = decl.strip()
    decl = re.sub(r"\bconst\b", "", decl).strip()
    stars = decl.count("*")
    base = decl.replace("*", "").strip()
    if base == "char" and stars == 1:
        return "c_char_p"
    if base == "void" and stars:
        return "c_void_p"
    if base in structs:
        inner = base[2:] if base.startswith("Sh") else base
        return ("POINTER(%s)" % inner) if stars else inner
    if base in CTYPE:
        t = CTYPE[base]
        if t is None:
            return "c_void_p" if stars else None
        return ("POINTER(%s)" % t) if stars else t
    # unknown types (function pointers, enums) pass as void*
    return "c_void_p" if stars else "c_int"


def parse_structs(text):
    out = {}
    pat = re.compile(r"typedef\s+struct\s*\{([^}]*)\}\s*(\w+)\s*;", re.S)
    for body, name in pat.findall(text):
        fields = []
        ok = True
        for line in body.split(";"):
            line = line.strip()
            if not line:
                continue
            m = re.match(r"([\w \t]+?[\w\*])\s+([\w, \t\[\]]+)$", line)
            if not m:
                ok = False
                break
            base, names = m.groups()
            for nm in names.split(","):
                nm = nm.strip()
                arr = re.match(r"(\w+)\s*\[(\w+)\]", nm)
                decl = base
                cnt = None
                if arr:
                    nm, cnt = arr.groups()
                t = ctype_of(decl, out)
                if t is None:
                    ok = False
                    break
                fields.append((nm, t, cnt))
            if not ok:
                break
        if ok and fields:
            out[name] = fields
    return out


def parse_funcs(text, structs):
    out = []
    pat = re.compile(r"SH_API\s+([\w \t\*]+?)\s+(Sh\w+)\s*\(([^;]*?)\)\s*;",
                     re.S)
    for ret, name, args in pat.findall(text):
        rt = ctype_of(ret, structs)
        ats = []
        args = " ".join(args.split())
        ok = True
        if args and args != "void":
            for a in args.split(","):
                a = a.strip()
                a = re.sub(r"\s*\w+$", "", a) if not a.endswith("*") else a
                t = ctype_of(a, structs)
                if t is None:
                    ok = False
                    break
                ats.append(t)
        if ok:
            out.append((name, rt, ats))
    return out


def main():
    src, dst = sys.argv[1], sys.argv[2]
    text = strip_comments(open(src).read())
    structs = parse_structs(text)
    funcs = parse_funcs(text, structs)

    w = open(dst, "w")
    w.write('"""ScriptHook bindings, generated by gen_sh.py. '
            'Edit the generator, never this file."""\n')
    w.write("import ctypes\nfrom ctypes import (POINTER, c_int, c_float,"
            " c_double, c_char, c_char_p,\n    c_void_p, c_uint8, c_uint16,"
            " c_uint32, c_uint64, c_int8, c_int16,\n    c_int32, c_int64,"
            " c_size_t)\n\n")
    w.write("_dll = ctypes.WinDLL('dinput8.dll')\n")
    w.write("_host = ctypes.WinDLL('pyhost.asi')\n")
    w.write("_host.PyHostGameDir.restype = ctypes.c_char_p\n\n")
    w.write("def log(msg):\n    _host.PyHostLog(str(msg).encode())\n\n")
    w.write("def plugin_dir():\n"
            "    import os\n"
            "    return os.path.join(_host.PyHostGameDir().decode(),"
            " 'plugins')\n\n")
    w.write("def q(addr):\n"
            "    return ctypes.c_uint64.from_address(addr).value\n\n")
    w.write("def f32(addr):\n"
            "    return ctypes.c_float.from_address(addr).value\n\n")

    for name, fields in structs.items():
        py = name[2:] if name.startswith("Sh") else name
        w.write("class %s(ctypes.Structure):\n    _fields_ = [\n" % py)
        for nm, t, cnt in fields:
            if cnt:
                w.write("        ('%s', %s * %s),\n" % (nm, t, cnt))
            else:
                w.write("        ('%s', %s),\n" % (nm, t))
        w.write("    ]\n\n")

    for name, rt, ats in funcs:
        py = name[2:]
        w.write("%s = _dll.%s\n" % (py, name))
        w.write("%s.restype = %s\n" % (py, rt if rt else "None"))
        if ats:
            w.write("%s.argtypes = [%s]\n" % (py, ", ".join(ats)))
        w.write("\n")
    w.close()
    print("sh.py: %d structs, %d functions" % (len(structs), len(funcs)))


if __name__ == "__main__":
    main()
