/* Entity enumeration, static paths only. Each entity
 * carries one component whose CLASS is its type.
 */
#include <windows.h>
#include <string.h>
#include <stdint.h>
#include <math.h>

#define SH_BUILD 1
#include "scripthook.h"

/* RVAs, so this survives a relocated image. */
#define RVA_PLAYER_MGR   0x4BB6438
#define RVA_VT_ENTITY    0x39C6FC8

#define OFF_MGR_WORLD    0x98
#define OFF_WORLD_LIST   0xBA0
#define OFF_WORLD_COUNT  0xBA8
#define OFF_ENT_POS      0x50
#define OFF_ENT_COMPS    0x78
#define OFF_ENT_NCOMPS   0x82
#define VT_GETDESC       0x30
#define OFF_DESC_HASH    0x24
#define OFF_ENT_NODE     0x18
#define OFF_NODE_LINK    0x68

extern int ShReadableAddr(uint64_t addr, size_t len);
extern uint64_t ShReadQ(uint64_t addr);
extern void ShSetError(int err);
extern int ShRequireInGame(void);
extern int ShGetHealthEntity(uint64_t entity, uint32_t *cur,
                             uint32_t *max);

static uint64_t ImgAddr(uint64_t rva) {
    return (uint64_t)(uintptr_t)GetModuleHandleA(NULL) + rva;
}

/* Link type 0 means no parent, so this is a root. Any
 * other type makes it a limb of something already listed.
 */
static int IsRoot(uint64_t entity) {
    uint64_t node;
    uint32_t type = 0;

    node = ShReadQ(entity + OFF_ENT_NODE);
    if (!node || !ShReadableAddr(node + OFF_NODE_LINK, 4)) return 1;
    memcpy(&type, (void *)(uintptr_t)(node + OFF_NODE_LINK), 4);
    return (type != 1 && type != 2);
}

/* Generated by nettypes.py from the image strings. */
static const struct {
    uint32_t hash;
    int kind;
    const char *name;
} g_kinds[] = {
    { 0x507DC2ECu, SH_KIND_PLAYER,    "Player"          },
    { 0xFEE4759Au, SH_KIND_NPC,       "NPC"             },
    { 0x8F2CBBBAu, SH_KIND_VEHICLE,   "Vehicle"         },
    { 0x5D621856u, SH_KIND_DRONE,     "Drone"           },
    { 0xEF953B76u, SH_KIND_TEAMMATE,  "Teammate"        },
    { 0x0186C7ACu, SH_KIND_TURRET,    "Turret"          },
    { 0xE6DBCF6Bu, SH_KIND_MINE,      "Mine"            },
    { 0x059648D5u, SH_KIND_DOOR,      "Door"            },
    { 0xCC586D4Au, SH_KIND_LOOTCHEST, "LootChest"       },
    { 0xA69E4386u, SH_KIND_OTHER,     "AlarmNet"        },
    { 0x7EDAAB74u, SH_KIND_OTHER,     "BearTrap"        },
    { 0x5644C87Fu, SH_KIND_OTHER,     "Codes"           },
    { 0xD839E268u, SH_KIND_OTHER,     "Destructible"    },
    { 0xD571F90Au, SH_KIND_OTHER,     "DominationPoint" },
    { 0xEB9D9BC9u, SH_KIND_OTHER,     "DroneJammer"     },
    { 0xFC1DFB0Du, SH_KIND_OTHER,     "Dummy"           },
    { 0x84C5EE35u, SH_KIND_OTHER,     "DynamicEvent"    },
    { 0xB22CC0B5u, SH_KIND_OTHER,     "EMPBlast"        },
    { 0xCAE95025u, SH_KIND_OTHER,     "ElectricDevice"  },
    { 0xB6E07575u, SH_KIND_OTHER,     "ExtractionPoint" },
    { 0x7B8D1BCDu, SH_KIND_OTHER,     "Flare"           },
    { 0xD19EB2D4u, SH_KIND_OTHER,     "FlareGun"        },
    { 0x19362348u, SH_KIND_OTHER,     "HackedServer"    },
    { 0x1F4B1328u, SH_KIND_OTHER,     "InteractiveElem" },
    { 0x4029E6AEu, SH_KIND_OTHER,     "LightPanel"      },
    { 0xA23FCD3Du, SH_KIND_OTHER,     "MagSensorNade"   },
    { 0x7C1D8BE9u, SH_KIND_OTHER,     "MercenaryAmmo"   },
    { 0x86EB450Au, SH_KIND_OTHER,     "MercAttachment"  },
    { 0x8D7F33FCu, SH_KIND_OTHER,     "MercCountable"   },
    { 0x8C89D0DDu, SH_KIND_OTHER,     "MercenaryItem"   },
    { 0x35A02C34u, SH_KIND_OTHER,     "MercenaryLoot"   },
    { 0x4433B66Au, SH_KIND_OTHER,     "MercenaryWeapon" },
    { 0x2F0FA0B5u, SH_KIND_OTHER,     "MineAdv"         },
    { 0x868D075Fu, SH_KIND_OTHER,     "Mortar"          },
    { 0xDA86CE85u, SH_KIND_OTHER,     "OrdersBeacon"    },
    { 0x04877609u, SH_KIND_OTHER,     "PVPHostage"      },
    { 0xCA10AECDu, SH_KIND_OTHER,     "PVPPrisonCell"   },
    { 0xF9789C28u, SH_KIND_OTHER,     "PlayerLoot"      },
    { 0xE162A6A3u, SH_KIND_OTHER,     "RCED"            },
    { 0xB631BC8Cu, SH_KIND_OTHER,     "RCEDAdv"         },
    { 0xD3D3F022u, SH_KIND_OTHER,     "RemoteJammer"    },
    { 0x8FE59CC6u, SH_KIND_OTHER,     "ResourceDrop"    },
    { 0x3D328332u, SH_KIND_OTHER,     "ResupplyDrop"    },
    { 0x9DE70FD6u, SH_KIND_OTHER,     "SAMLauncher"     },
    { 0x8211F572u, SH_KIND_OTHER,     "SatComTracker"   },
    { 0x84299CADu, SH_KIND_OTHER,     "SearchLight"     },
    { 0x3591E249u, SH_KIND_OTHER,     "Throwable"       },
    { 0xAF802229u, SH_KIND_OTHER,     "Tool"            },
    { 0x5E2209ADu, SH_KIND_OTHER,     "Tripwire"        },
    { 0xF033F1E9u, SH_KIND_OTHER,     "WeaponDrop"      },
    { 0xB6BC2554u, SH_KIND_OTHER,     "WorldEvent"      },
};

#define NKINDS (int)(sizeof(g_kinds) / sizeof(g_kinds[0]))

/* vtable +0x30 thunks to a getter returning the class
 * descriptor, whose +0x24 holds the class hash.
 */
static uint32_t ClassHashOf(uint64_t obj) {
    uint64_t vt, thunk, tgt, desc;
    uint8_t b[16];
    int32_t rel, disp;
    uint32_t hash = 0;
    int i;

    if (!ShReadableAddr(obj, 8)) return 0;
    vt = ShReadQ(obj);
    if (!ShReadableAddr(vt + VT_GETDESC, 8)) return 0;
    thunk = ShReadQ(vt + VT_GETDESC);
    if (!ShReadableAddr(thunk, 8)) return 0;
    memcpy(b, (void *)(uintptr_t)thunk, 8);
    if (b[0] != 0xE9) return 0;
    memcpy(&rel, b + 1, 4);
    tgt = thunk + 5 + rel;
    if (!ShReadableAddr(tgt, 16)) return 0;
    memcpy(b, (void *)(uintptr_t)tgt, 16);
    for (i = 0; i + 7 <= 16; i++) {
        if (b[i] == 0x48 && b[i + 1] == 0x8B && b[i + 2] == 0x05) {
            memcpy(&disp, b + i + 3, 4);
            desc = ShReadQ(tgt + i + 7 + disp);
            if (ShReadableAddr(desc + OFF_DESC_HASH, 4))
                memcpy(&hash, (void *)(uintptr_t)
                       (desc + OFF_DESC_HASH), 4);
            return hash;
        }
    }
    return 0;
}

static int KindIndex(uint64_t entity) {
    uint64_t arr;
    uint16_t n = 0, i;
    int k;

    arr = ShReadQ(entity + OFF_ENT_COMPS);
    if (!arr || !ShReadableAddr(entity + OFF_ENT_NCOMPS, 2))
        return -1;
    memcpy(&n, (void *)(uintptr_t)(entity + OFF_ENT_NCOMPS), 2);
    if (!n || n > 512) return -1;

    for (i = 0; i < n; i++) {
        uint64_t c = ShReadQ(arr + (uint64_t)i * 8);
        uint32_t h;
        if (!c) continue;
        h = ClassHashOf(c);
        if (!h) continue;
        for (k = 0; k < NKINDS; k++)
            if (g_kinds[k].hash == h) return k;
    }
    return -1;
}

SH_API int ShGetComponents(uint64_t entity, ShComponent *out,
                           int max)
{
    uint64_t arr;
    uint16_t n = 0, i;
    int written = 0, k;

    if (!out || max <= 0) { ShSetError(SH_ERR_BAD_ARG); return 0; }
    if (!entity || !ShReadableAddr(entity, 0x90)) {
        ShSetError(SH_ERR_NOT_ENTITY);
        return 0;
    }
    arr = ShReadQ(entity + OFF_ENT_COMPS);
    if (!arr || !ShReadableAddr(entity + OFF_ENT_NCOMPS, 2)) {
        ShSetError(SH_ERR_NO_CANDIDATE);
        return 0;
    }
    memcpy(&n, (void *)(uintptr_t)(entity + OFF_ENT_NCOMPS), 2);
    if (!n || n > 512) { ShSetError(SH_ERR_NO_CANDIDATE); return 0; }

    for (i = 0; i < n && written < max; i++) {
        uint64_t c = ShReadQ(arr + (uint64_t)i * 8);
        if (!c) continue;
        memset(&out[written], 0, sizeof(out[written]));
        out[written].component = c;
        out[written].dataBlock = ShReadQ(c + 0x20);
        out[written].classHash = ClassHashOf(c);
        for (k = 0; k < NKINDS; k++) {
            if (g_kinds[k].hash != out[written].classHash) continue;
            strncpy(out[written].name, g_kinds[k].name,
                    sizeof(out[written].name) - 1);
            break;
        }
        written++;
    }
    return written;
}

SH_API uint64_t ShFindComponent(uint64_t entity,
                                uint32_t classHash)
{
    uint64_t arr;
    uint16_t n = 0, i;

    if (!entity || !ShReadableAddr(entity, 0x90)) {
        ShSetError(SH_ERR_NOT_ENTITY);
        return 0;
    }
    arr = ShReadQ(entity + OFF_ENT_COMPS);
    if (!arr || !ShReadableAddr(entity + OFF_ENT_NCOMPS, 2)) return 0;
    memcpy(&n, (void *)(uintptr_t)(entity + OFF_ENT_NCOMPS), 2);
    if (!n || n > 512) return 0;

    for (i = 0; i < n; i++) {
        uint64_t c = ShReadQ(arr + (uint64_t)i * 8);
        if (c && ClassHashOf(c) == classHash) return c;
    }
    return 0;
}

SH_API int ShGetEntityKind(uint64_t entity) {
    int k;
    if (!entity || !ShReadableAddr(entity, 0x90)) return SH_KIND_ANY;
    k = KindIndex(entity);
    return k < 0 ? SH_KIND_ANY : g_kinds[k].kind;
}

SH_API const char *ShKindName(int kind) {
    switch (kind) {
    case SH_KIND_PLAYER:    return "Player";
    case SH_KIND_NPC:       return "NPC";
    case SH_KIND_VEHICLE:   return "Vehicle";
    case SH_KIND_DRONE:     return "Drone";
    case SH_KIND_TEAMMATE:  return "Teammate";
    case SH_KIND_TURRET:    return "Turret";
    case SH_KIND_MINE:      return "Mine";
    case SH_KIND_DOOR:      return "Door";
    case SH_KIND_LOOTCHEST: return "LootChest";
    case SH_KIND_OTHER:     return "Other";
    }
    return "Any";
}

static int WorldList(uint64_t *outList, uint32_t *outCount) {
    uint64_t mgr, world, lst;
    uint16_t n = 0;

    mgr = ShReadQ(ImgAddr(RVA_PLAYER_MGR));
    if (!mgr) return 0;
    world = ShReadQ(mgr + OFF_MGR_WORLD);
    if (!world) return 0;
    lst = ShReadQ(world + OFF_WORLD_LIST);
    if (!lst || !ShReadableAddr(world + OFF_WORLD_COUNT, 2))
        return 0;
    memcpy(&n, (void *)(uintptr_t)(world + OFF_WORLD_COUNT), 2);
    if (!n || n > 4096) return 0;
    *outList = lst;
    *outCount = n;
    return 1;
}

SH_API int ShFindEntities(int kind, float radius, uint32_t flags,
                          ShEntity *out, int max) {
    uint64_t lst = 0, vtEnt;
    uint32_t cnt = 0, i;
    ShVec3 me;
    int n = 0;

    if (!out || max <= 0) { ShSetError(SH_ERR_BAD_ARG); return 0; }
    if (!ShRequireInGame()) return 0;
    if (!WorldList(&lst, &cnt)) {
        ShSetError(SH_ERR_NO_GLOBAL);
        return 0;
    }
    if (!ShGetPlayerPosition(&me)) return 0;
    if (radius <= 0.0f) radius = 1e9f;
    vtEnt = ImgAddr(RVA_VT_ENTITY);

    for (i = 0; i < cnt && n < max; i++) {
        uint64_t e = ShReadQ(lst + (uint64_t)i * 8);
        float p[3], dx, dy, dz, d;
        uint32_t cur = 0, mx = 0;
        int ki, j;

        if (!e || !ShReadableAddr(e, 0x90)) continue;
        if (ShReadQ(e) != vtEnt) continue;
        memcpy(p, (void *)(uintptr_t)(e + OFF_ENT_POS), 12);
        dx = p[0] - me.x;
        dy = p[1] - me.y;
        dz = p[2] - me.z;
        d = sqrtf(dx * dx + dy * dy + dz * dz);
        if (d > radius) continue;

        /* Skip limbs, they are parts of a listed entity. */
        if (!IsRoot(e)) continue;

        ki = KindIndex(e);
        if (ki < 0 && !(flags & SH_FIND_UNNAMED)) continue;
        if (kind != SH_KIND_ANY
            && (ki < 0 || g_kinds[ki].kind != kind)) continue;

        ShGetHealthEntity(e, &cur, &mx);

        /* Insertion sort, nearest first. */
        for (j = n; j > 0 && out[j - 1].distance > d; j--)
            if (j < max) out[j] = out[j - 1];
        if (j >= max) continue;
        out[j].entity = e;
        out[j].pos.x = p[0];
        out[j].pos.y = p[1];
        out[j].pos.z = p[2];
        out[j].distance = d;
        out[j].kind = ki < 0 ? SH_KIND_ANY : g_kinds[ki].kind;
        out[j].maxHealth = mx;
        memset(out[j].name, 0, sizeof(out[j].name));
        if (ki >= 0)
            strncpy(out[j].name, g_kinds[ki].name,
                    sizeof(out[j].name) - 1);
        if (n < max) n++;
    }
    ShSetError(SH_OK);
    return n;
}
