/* Generated by out/nightvision/_work/lut/gen_looks.py - do not edit by hand.
 *
 * The game's Photo Mode filters are 32x32x32 B8G8R8A8 look-up cubes. Night
 * vision works on ONE scalar, so only a cube's grey axis - the texel (i,i,i) of
 * each entry - can reach the screen, and that axis is what is tabulated here:
 * 32 samples, one lerp. Measured against the engine's trilinear sample: at most
 * 1.05/255 apart.
 *
 * A table, not a polynomial: these grades are split-tone (blue shadows, warm
 * highlights) and polynomials will not follow them - a degree-5 fit still
 * misses one of them by 12/255.
 *
 * The expression looks (see nv_filter_ps.hlsl, which defines them before this
 * file is included) are referenced from the dispatch the same way.
 *
 * Regenerate with `python gen_looks.py` after re-running extract_all.py.
 */

#ifndef NV_LOOKS_HLSL
#define NV_LOOKS_HLSL

/* mode  ini key          */
#define NV_LOOK_BLACK_AND_WHITE 1  /* black-and-white */
#define NV_LOOK_YELLOW_GREEN    2  /* yellow-green */
#define NV_LOOK_SEPIA           3  /* sepia */
#define NV_LOOK_APOLLO          4  /* apollo */
#define NV_LOOK_LIGHTHOUSE      5  /* lighthouse */
#define NV_LOOK_TENNESSEE       6  /* tennessee */
#define NV_LOOK_ARLINGTON       7  /* arlington */
#define NV_LOOK_BRIDGE          8  /* bridge */
#define NV_LOOK_MONTENEGRO      9  /* montenegro */
#define NV_LOOK_CHIEF           10 /* chief */
#define NV_LOOK_SONGBIRD        11 /* songbird */
#define NV_LOOK_MADRE           12 /* madre */
#define NV_LOOK_BURNER          13 /* burner */
#define NV_LOOK_NEUTRAL         14 /* neutral */
#define NV_LOOK_AMBER           15 /* amber */
#define NV_LOOK_COOLBLUE        16 /* cool-blue */
#define NV_LOOK_CONTRAST        17 /* contrast */

/* sepia - the grey axis of the Photo Mode "SEPIA" look-up cube. */
static const float3 kLookSEPIA[32] = {
    {0.000000f, 0.000000f, 0.000000f}, {0.039216f, 0.031373f, 0.027451f}, {0.074510f, 0.062745f, 0.050980f}, {0.113725f, 0.094118f, 0.078431f},
    {0.149020f, 0.125490f, 0.101961f}, {0.192157f, 0.160784f, 0.133333f}, {0.227451f, 0.192157f, 0.156863f}, {0.266667f, 0.223529f, 0.184314f},
    {0.301961f, 0.254902f, 0.207843f}, {0.345098f, 0.290196f, 0.239216f}, {0.380392f, 0.321569f, 0.262745f}, {0.419608f, 0.352941f, 0.286275f},
    {0.458824f, 0.384314f, 0.313725f}, {0.494118f, 0.415686f, 0.337255f}, {0.537255f, 0.450980f, 0.368627f}, {0.572549f, 0.482353f, 0.392157f},
    {0.603922f, 0.513725f, 0.423529f}, {0.631373f, 0.545098f, 0.462745f}, {0.658824f, 0.580392f, 0.501961f}, {0.686275f, 0.611765f, 0.541176f},
    {0.709804f, 0.643137f, 0.576471f}, {0.737255f, 0.674510f, 0.615686f}, {0.760784f, 0.705882f, 0.650980f}, {0.788235f, 0.741176f, 0.694118f},
    {0.815686f, 0.772549f, 0.733333f}, {0.839216f, 0.803922f, 0.768627f}, {0.866667f, 0.835294f, 0.807843f}, {0.894118f, 0.870588f, 0.847059f},
    {0.921569f, 0.901961f, 0.886275f}, {0.945098f, 0.933333f, 0.921569f}, {0.972549f, 0.964706f, 0.960784f}, {1.000000f, 1.000000f, 1.000000f}
};

float3 LookSEPIA(float g, float white)
{
    float x = saturate(g / white) * 31.0;
    int   i = (int)x;
    return lerp(kLookSEPIA[i], kLookSEPIA[min(i + 1, 31)], x - (float)i);
}
/* apollo - the grey axis of the Photo Mode "APOLLO" look-up cube. */
static const float3 kLookAPOLLO[32] = {
    {0.168627f, 0.168627f, 0.168627f}, {0.168627f, 0.168627f, 0.168627f}, {0.172549f, 0.172549f, 0.172549f}, {0.180392f, 0.180392f, 0.180392f},
    {0.184314f, 0.184314f, 0.184314f}, {0.196078f, 0.196078f, 0.196078f}, {0.207843f, 0.207843f, 0.207843f}, {0.235294f, 0.235294f, 0.235294f},
    {0.254902f, 0.254902f, 0.254902f}, {0.286275f, 0.286275f, 0.286275f}, {0.317647f, 0.317647f, 0.317647f}, {0.349020f, 0.349020f, 0.349020f},
    {0.372549f, 0.372549f, 0.372549f}, {0.400000f, 0.400000f, 0.400000f}, {0.431373f, 0.431373f, 0.431373f}, {0.462745f, 0.462745f, 0.462745f},
    {0.501961f, 0.501961f, 0.501961f}, {0.541176f, 0.541176f, 0.541176f}, {0.576471f, 0.576471f, 0.576471f}, {0.619608f, 0.619608f, 0.619608f},
    {0.654902f, 0.654902f, 0.654902f}, {0.690196f, 0.690196f, 0.690196f}, {0.725490f, 0.725490f, 0.725490f}, {0.752941f, 0.752941f, 0.752941f},
    {0.784314f, 0.784314f, 0.784314f}, {0.811765f, 0.811765f, 0.811765f}, {0.835294f, 0.835294f, 0.835294f}, {0.866667f, 0.866667f, 0.866667f},
    {0.890196f, 0.890196f, 0.890196f}, {0.917647f, 0.917647f, 0.917647f}, {0.933333f, 0.933333f, 0.933333f}, {0.964706f, 0.964706f, 0.964706f}
};

float3 LookAPOLLO(float g, float white)
{
    float x = saturate(g / white) * 31.0;
    int   i = (int)x;
    return lerp(kLookAPOLLO[i], kLookAPOLLO[min(i + 1, 31)], x - (float)i);
}
/* lighthouse - the grey axis of the Photo Mode "LIGHTHOUSE" look-up cube. */
static const float3 kLookLIGHTHOUSE[32] = {
    {0.000000f, 0.109804f, 0.137255f}, {0.000000f, 0.109804f, 0.141176f}, {0.000000f, 0.113725f, 0.145098f}, {0.023529f, 0.121569f, 0.149020f},
    {0.078431f, 0.137255f, 0.160784f}, {0.133333f, 0.168627f, 0.180392f}, {0.176471f, 0.196078f, 0.200000f}, {0.215686f, 0.227451f, 0.231373f},
    {0.247059f, 0.258824f, 0.258824f}, {0.282353f, 0.290196f, 0.290196f}, {0.317647f, 0.325490f, 0.325490f}, {0.349020f, 0.356863f, 0.356863f},
    {0.376471f, 0.388235f, 0.388235f}, {0.407843f, 0.419608f, 0.423529f}, {0.447059f, 0.450980f, 0.458824f}, {0.482353f, 0.482353f, 0.490196f},
    {0.513725f, 0.509804f, 0.525490f}, {0.545098f, 0.541176f, 0.556863f}, {0.580392f, 0.576471f, 0.592157f}, {0.615686f, 0.607843f, 0.627451f},
    {0.643137f, 0.639216f, 0.654902f}, {0.678431f, 0.670588f, 0.690196f}, {0.709804f, 0.698039f, 0.717647f}, {0.749020f, 0.737255f, 0.756863f},
    {0.776471f, 0.768627f, 0.780392f}, {0.807843f, 0.800000f, 0.811765f}, {0.839216f, 0.831373f, 0.839216f}, {0.870588f, 0.866667f, 0.874510f},
    {0.901961f, 0.898039f, 0.901961f}, {0.925490f, 0.925490f, 0.925490f}, {0.945098f, 0.945098f, 0.945098f}, {0.960784f, 0.960784f, 0.960784f}
};

float3 LookLIGHTHOUSE(float g, float white)
{
    float x = saturate(g / white) * 31.0;
    int   i = (int)x;
    return lerp(kLookLIGHTHOUSE[i], kLookLIGHTHOUSE[min(i + 1, 31)], x - (float)i);
}
/* tennessee - the grey axis of the Photo Mode "TENNESSEE" look-up cube. */
static const float3 kLookTENNESSEE[32] = {
    {0.137255f, 0.086275f, 0.254902f}, {0.137255f, 0.086275f, 0.254902f}, {0.137255f, 0.086275f, 0.254902f}, {0.137255f, 0.121569f, 0.254902f},
    {0.137255f, 0.152941f, 0.270588f}, {0.137255f, 0.192157f, 0.294118f}, {0.137255f, 0.223529f, 0.317647f}, {0.137255f, 0.258824f, 0.337255f},
    {0.137255f, 0.290196f, 0.360784f}, {0.192157f, 0.325490f, 0.384314f}, {0.247059f, 0.360784f, 0.407843f}, {0.301961f, 0.392157f, 0.427451f},
    {0.356863f, 0.423529f, 0.447059f}, {0.407843f, 0.454902f, 0.470588f}, {0.462745f, 0.490196f, 0.494118f}, {0.509804f, 0.517647f, 0.513725f},
    {0.556863f, 0.549020f, 0.537255f}, {0.600000f, 0.576471f, 0.556863f}, {0.643137f, 0.611765f, 0.580392f}, {0.682353f, 0.639216f, 0.600000f},
    {0.717647f, 0.666667f, 0.619608f}, {0.752941f, 0.694118f, 0.643137f}, {0.784314f, 0.717647f, 0.662745f}, {0.815686f, 0.749020f, 0.686275f},
    {0.847059f, 0.776471f, 0.705882f}, {0.874510f, 0.800000f, 0.725490f}, {0.898039f, 0.827451f, 0.745098f}, {0.929412f, 0.854902f, 0.768627f},
    {0.952941f, 0.882353f, 0.788235f}, {0.980392f, 0.905882f, 0.807843f}, {1.000000f, 0.929412f, 0.827451f}, {1.000000f, 0.952941f, 0.850980f}
};

float3 LookTENNESSEE(float g, float white)
{
    float x = saturate(g / white) * 31.0;
    int   i = (int)x;
    return lerp(kLookTENNESSEE[i], kLookTENNESSEE[min(i + 1, 31)], x - (float)i);
}
/* arlington - the grey axis of the Photo Mode "ARLINGTON" look-up cube. */
static const float3 kLookARLINGTON[32] = {
    {0.000000f, 0.000000f, 0.094118f}, {0.000000f, 0.031373f, 0.117647f}, {0.000000f, 0.058824f, 0.141176f}, {0.000000f, 0.086275f, 0.156863f},
    {0.000000f, 0.117647f, 0.184314f}, {0.015686f, 0.149020f, 0.207843f}, {0.066667f, 0.180392f, 0.227451f}, {0.113725f, 0.211765f, 0.254902f},
    {0.152941f, 0.243137f, 0.278431f}, {0.203922f, 0.290196f, 0.301961f}, {0.254902f, 0.329412f, 0.333333f}, {0.294118f, 0.364706f, 0.352941f},
    {0.345098f, 0.411765f, 0.380392f}, {0.392157f, 0.450980f, 0.411765f}, {0.435294f, 0.494118f, 0.447059f}, {0.486275f, 0.529412f, 0.474510f},
    {0.525490f, 0.564706f, 0.505882f}, {0.552941f, 0.592157f, 0.537255f}, {0.588235f, 0.627451f, 0.580392f}, {0.615686f, 0.647059f, 0.619608f},
    {0.639216f, 0.674510f, 0.650980f}, {0.666667f, 0.705882f, 0.686275f}, {0.694118f, 0.729412f, 0.721569f}, {0.725490f, 0.756863f, 0.764706f},
    {0.756863f, 0.776471f, 0.796078f}, {0.784314f, 0.807843f, 0.831373f}, {0.815686f, 0.835294f, 0.850980f}, {0.847059f, 0.866667f, 0.886275f},
    {0.882353f, 0.898039f, 0.913725f}, {0.913725f, 0.929412f, 0.941176f}, {0.945098f, 0.956863f, 0.968627f}, {0.980392f, 0.992157f, 0.992157f}
};

float3 LookARLINGTON(float g, float white)
{
    float x = saturate(g / white) * 31.0;
    int   i = (int)x;
    return lerp(kLookARLINGTON[i], kLookARLINGTON[min(i + 1, 31)], x - (float)i);
}
/* bridge - the grey axis of the Photo Mode "BRIDGE" look-up cube. */
static const float3 kLookBRIDGE[32] = {
    {0.043137f, 0.070588f, 0.066667f}, {0.094118f, 0.086275f, 0.094118f}, {0.145098f, 0.105882f, 0.129412f}, {0.196078f, 0.125490f, 0.164706f},
    {0.243137f, 0.149020f, 0.196078f}, {0.290196f, 0.180392f, 0.239216f}, {0.329412f, 0.215686f, 0.270588f}, {0.356863f, 0.254902f, 0.309804f},
    {0.384314f, 0.298039f, 0.349020f}, {0.415686f, 0.349020f, 0.388235f}, {0.435294f, 0.396078f, 0.431373f}, {0.458824f, 0.439216f, 0.466667f},
    {0.474510f, 0.486275f, 0.501961f}, {0.498039f, 0.521569f, 0.529412f}, {0.521569f, 0.564706f, 0.564706f}, {0.537255f, 0.600000f, 0.596078f},
    {0.564706f, 0.631373f, 0.611765f}, {0.596078f, 0.666667f, 0.631373f}, {0.623529f, 0.698039f, 0.654902f}, {0.658824f, 0.729412f, 0.670588f},
    {0.690196f, 0.756863f, 0.686275f}, {0.721569f, 0.780392f, 0.698039f}, {0.760784f, 0.803922f, 0.717647f}, {0.800000f, 0.835294f, 0.741176f},
    {0.835294f, 0.858824f, 0.768627f}, {0.870588f, 0.878431f, 0.792157f}, {0.909804f, 0.905882f, 0.823529f}, {0.952941f, 0.937255f, 0.858824f},
    {0.984314f, 0.956863f, 0.886275f}, {1.000000f, 0.984314f, 0.921569f}, {1.000000f, 1.000000f, 0.952941f}, {1.000000f, 1.000000f, 0.988235f}
};

float3 LookBRIDGE(float g, float white)
{
    float x = saturate(g / white) * 31.0;
    int   i = (int)x;
    return lerp(kLookBRIDGE[i], kLookBRIDGE[min(i + 1, 31)], x - (float)i);
}
/* montenegro - the grey axis of the Photo Mode "MONTENEGRO" look-up cube. */
static const float3 kLookMONTENEGRO[32] = {
    {0.094118f, 0.000000f, 0.000000f}, {0.129412f, 0.043137f, 0.054902f}, {0.160784f, 0.078431f, 0.121569f}, {0.192157f, 0.121569f, 0.168627f},
    {0.227451f, 0.164706f, 0.219608f}, {0.262745f, 0.203922f, 0.266667f}, {0.294118f, 0.235294f, 0.305882f}, {0.321569f, 0.278431f, 0.337255f},
    {0.352941f, 0.317647f, 0.364706f}, {0.384314f, 0.360784f, 0.388235f}, {0.411765f, 0.403922f, 0.407843f}, {0.439216f, 0.439216f, 0.427451f},
    {0.470588f, 0.474510f, 0.447059f}, {0.501961f, 0.521569f, 0.474510f}, {0.533333f, 0.556863f, 0.501961f}, {0.560784f, 0.588235f, 0.521569f},
    {0.592157f, 0.619608f, 0.545098f}, {0.615686f, 0.643137f, 0.568627f}, {0.647059f, 0.674510f, 0.603922f}, {0.674510f, 0.698039f, 0.631373f},
    {0.701961f, 0.721569f, 0.662745f}, {0.729412f, 0.749020f, 0.694118f}, {0.756863f, 0.772549f, 0.733333f}, {0.788235f, 0.800000f, 0.768627f},
    {0.811765f, 0.823529f, 0.800000f}, {0.831373f, 0.847059f, 0.831373f}, {0.858824f, 0.870588f, 0.862745f}, {0.886275f, 0.898039f, 0.905882f},
    {0.913725f, 0.925490f, 0.941176f}, {0.933333f, 0.949020f, 0.972549f}, {0.960784f, 0.972549f, 1.000000f}, {0.972549f, 0.984314f, 1.000000f}
};

float3 LookMONTENEGRO(float g, float white)
{
    float x = saturate(g / white) * 31.0;
    int   i = (int)x;
    return lerp(kLookMONTENEGRO[i], kLookMONTENEGRO[min(i + 1, 31)], x - (float)i);
}
/* chief - the grey axis of the Photo Mode "CHIEF" look-up cube. */
static const float3 kLookCHIEF[32] = {
    {0.000000f, 0.000000f, 0.000000f}, {0.000000f, 0.000000f, 0.000000f}, {0.019608f, 0.000000f, 0.000000f}, {0.062745f, 0.000000f, 0.000000f},
    {0.105882f, 0.019608f, 0.000000f}, {0.152941f, 0.062745f, 0.000000f}, {0.192157f, 0.105882f, 0.003922f}, {0.227451f, 0.141176f, 0.043137f},
    {0.266667f, 0.176471f, 0.082353f}, {0.305882f, 0.223529f, 0.125490f}, {0.337255f, 0.258824f, 0.164706f}, {0.372549f, 0.298039f, 0.200000f},
    {0.407843f, 0.329412f, 0.239216f}, {0.443137f, 0.364706f, 0.278431f}, {0.474510f, 0.407843f, 0.321569f}, {0.509804f, 0.443137f, 0.360784f},
    {0.541176f, 0.474510f, 0.400000f}, {0.576471f, 0.509804f, 0.439216f}, {0.607843f, 0.549020f, 0.482353f}, {0.639216f, 0.588235f, 0.517647f},
    {0.670588f, 0.619608f, 0.556863f}, {0.698039f, 0.650980f, 0.596078f}, {0.729412f, 0.686275f, 0.635294f}, {0.764706f, 0.725490f, 0.682353f},
    {0.792157f, 0.756863f, 0.721569f}, {0.823529f, 0.792157f, 0.760784f}, {0.850980f, 0.823529f, 0.800000f}, {0.882353f, 0.866667f, 0.843137f},
    {0.909804f, 0.898039f, 0.878431f}, {0.941176f, 0.925490f, 0.917647f}, {0.968627f, 0.964706f, 0.956863f}, {1.000000f, 1.000000f, 1.000000f}
};

float3 LookCHIEF(float g, float white)
{
    float x = saturate(g / white) * 31.0;
    int   i = (int)x;
    return lerp(kLookCHIEF[i], kLookCHIEF[min(i + 1, 31)], x - (float)i);
}
/* songbird - the grey axis of the Photo Mode "SONGBIRD" look-up cube. */
static const float3 kLookSONGBIRD[32] = {
    {0.000000f, 0.000000f, 0.000000f}, {0.000000f, 0.007843f, 0.031373f}, {0.031373f, 0.066667f, 0.066667f}, {0.086275f, 0.113725f, 0.098039f},
    {0.137255f, 0.160784f, 0.133333f}, {0.188235f, 0.203922f, 0.168627f}, {0.227451f, 0.243137f, 0.203922f}, {0.270588f, 0.278431f, 0.235294f},
    {0.309804f, 0.317647f, 0.270588f}, {0.352941f, 0.360784f, 0.305882f}, {0.388235f, 0.396078f, 0.341176f}, {0.427451f, 0.427451f, 0.372549f},
    {0.466667f, 0.466667f, 0.407843f}, {0.501961f, 0.498039f, 0.439216f}, {0.545098f, 0.529412f, 0.478431f}, {0.576471f, 0.564706f, 0.509804f},
    {0.615686f, 0.596078f, 0.545098f}, {0.647059f, 0.631373f, 0.576471f}, {0.686275f, 0.662745f, 0.615686f}, {0.717647f, 0.694118f, 0.647059f},
    {0.752941f, 0.721569f, 0.682353f}, {0.784314f, 0.756863f, 0.713725f}, {0.815686f, 0.784314f, 0.745098f}, {0.854902f, 0.815686f, 0.784314f},
    {0.886275f, 0.847059f, 0.815686f}, {0.921569f, 0.878431f, 0.850980f}, {0.952941f, 0.909804f, 0.882353f}, {0.988235f, 0.941176f, 0.921569f},
    {1.000000f, 0.968627f, 0.952941f}, {1.000000f, 1.000000f, 0.988235f}, {1.000000f, 1.000000f, 1.000000f}, {1.000000f, 1.000000f, 1.000000f}
};

float3 LookSONGBIRD(float g, float white)
{
    float x = saturate(g / white) * 31.0;
    int   i = (int)x;
    return lerp(kLookSONGBIRD[i], kLookSONGBIRD[min(i + 1, 31)], x - (float)i);
}
/* madre - the grey axis of the Photo Mode "MADRE" look-up cube. */
static const float3 kLookMADRE[32] = {
    {0.000000f, 0.050980f, 0.000000f}, {0.031373f, 0.050980f, 0.066667f}, {0.105882f, 0.050980f, 0.113725f}, {0.168627f, 0.101961f, 0.156863f},
    {0.207843f, 0.156863f, 0.196078f}, {0.262745f, 0.207843f, 0.235294f}, {0.309804f, 0.254902f, 0.266667f}, {0.345098f, 0.294118f, 0.301961f},
    {0.384314f, 0.337255f, 0.337255f}, {0.423529f, 0.376471f, 0.372549f}, {0.454902f, 0.415686f, 0.403922f}, {0.494118f, 0.450980f, 0.435294f},
    {0.521569f, 0.486275f, 0.466667f}, {0.556863f, 0.517647f, 0.498039f}, {0.596078f, 0.556863f, 0.529412f}, {0.623529f, 0.588235f, 0.560784f},
    {0.650980f, 0.615686f, 0.588235f}, {0.682353f, 0.643137f, 0.615686f}, {0.709804f, 0.678431f, 0.647059f}, {0.741176f, 0.705882f, 0.674510f},
    {0.768627f, 0.733333f, 0.701961f}, {0.796078f, 0.756863f, 0.729412f}, {0.823529f, 0.784314f, 0.756863f}, {0.847059f, 0.807843f, 0.788235f},
    {0.874510f, 0.835294f, 0.811765f}, {0.901961f, 0.858824f, 0.839216f}, {0.925490f, 0.882353f, 0.866667f}, {0.949020f, 0.909804f, 0.898039f},
    {0.972549f, 0.933333f, 0.921569f}, {1.000000f, 0.952941f, 0.949020f}, {1.000000f, 0.976471f, 0.972549f}, {1.000000f, 1.000000f, 1.000000f}
};

float3 LookMADRE(float g, float white)
{
    float x = saturate(g / white) * 31.0;
    int   i = (int)x;
    return lerp(kLookMADRE[i], kLookMADRE[min(i + 1, 31)], x - (float)i);
}
/* burner - the grey axis of the Photo Mode "BURNER" look-up cube. */
static const float3 kLookBURNER[32] = {
    {0.070588f, 0.003922f, 0.015686f}, {0.094118f, 0.027451f, 0.035294f}, {0.129412f, 0.039216f, 0.054902f}, {0.164706f, 0.054902f, 0.078431f},
    {0.203922f, 0.074510f, 0.098039f}, {0.247059f, 0.098039f, 0.125490f}, {0.290196f, 0.117647f, 0.145098f}, {0.329412f, 0.137255f, 0.172549f},
    {0.372549f, 0.164706f, 0.196078f}, {0.411765f, 0.203922f, 0.227451f}, {0.443137f, 0.250980f, 0.250980f}, {0.482353f, 0.294118f, 0.278431f},
    {0.517647f, 0.349020f, 0.301961f}, {0.552941f, 0.403922f, 0.333333f}, {0.584314f, 0.470588f, 0.360784f}, {0.611765f, 0.525490f, 0.392157f},
    {0.639216f, 0.568627f, 0.415686f}, {0.666667f, 0.607843f, 0.447059f}, {0.698039f, 0.635294f, 0.482353f}, {0.725490f, 0.658824f, 0.513725f},
    {0.749020f, 0.682353f, 0.545098f}, {0.772549f, 0.701961f, 0.576471f}, {0.792157f, 0.725490f, 0.615686f}, {0.819608f, 0.745098f, 0.658824f},
    {0.835294f, 0.764706f, 0.694118f}, {0.854902f, 0.788235f, 0.733333f}, {0.870588f, 0.811765f, 0.772549f}, {0.890196f, 0.839216f, 0.815686f},
    {0.905882f, 0.870588f, 0.854902f}, {0.921569f, 0.898039f, 0.890196f}, {0.945098f, 0.925490f, 0.925490f}, {0.960784f, 0.960784f, 0.956863f}
};

float3 LookBURNER(float g, float white)
{
    float x = saturate(g / white) * 31.0;
    int   i = (int)x;
    return lerp(kLookBURNER[i], kLookBURNER[min(i + 1, 31)], x - (float)i);
}
/* neutral - the grey axis of the Photo Mode "BLACKandWHITE" look-up cube. */
static const float3 kLookNEUTRAL[32] = {
    {0.000000f, 0.000000f, 0.000000f}, {0.031373f, 0.031373f, 0.031373f}, {0.062745f, 0.062745f, 0.062745f}, {0.094118f, 0.094118f, 0.094118f},
    {0.125490f, 0.125490f, 0.125490f}, {0.160784f, 0.160784f, 0.160784f}, {0.192157f, 0.192157f, 0.192157f}, {0.223529f, 0.223529f, 0.223529f},
    {0.254902f, 0.254902f, 0.254902f}, {0.290196f, 0.290196f, 0.290196f}, {0.321569f, 0.321569f, 0.321569f}, {0.352941f, 0.352941f, 0.352941f},
    {0.384314f, 0.384314f, 0.384314f}, {0.415686f, 0.415686f, 0.415686f}, {0.450980f, 0.450980f, 0.450980f}, {0.482353f, 0.482353f, 0.482353f},
    {0.513725f, 0.513725f, 0.513725f}, {0.545098f, 0.545098f, 0.545098f}, {0.580392f, 0.580392f, 0.580392f}, {0.611765f, 0.611765f, 0.611765f},
    {0.643137f, 0.643137f, 0.643137f}, {0.674510f, 0.674510f, 0.674510f}, {0.705882f, 0.705882f, 0.705882f}, {0.741176f, 0.741176f, 0.741176f},
    {0.772549f, 0.772549f, 0.772549f}, {0.803922f, 0.803922f, 0.803922f}, {0.835294f, 0.835294f, 0.835294f}, {0.870588f, 0.870588f, 0.870588f},
    {0.901961f, 0.901961f, 0.901961f}, {0.933333f, 0.933333f, 0.933333f}, {0.964706f, 0.964706f, 0.964706f}, {1.000000f, 1.000000f, 1.000000f}
};

float3 LookNEUTRAL(float g, float white)
{
    float x = saturate(g / white) * 31.0;
    int   i = (int)x;
    return lerp(kLookNEUTRAL[i], kLookNEUTRAL[min(i + 1, 31)], x - (float)i);
}

/* Which look this build puts there, decided before the shader is compiled.
 * `mono` and `ramp` are the engine's own two looks: with NV_ALL_MODES off,
 * modes 1 and 2 keep them, so this variant has to be able to produce them.
 * With it on, nothing can ask for them and they fall away with the branch. */
float3 LookSelected(int mode, float g, float3 gray, float3 tint)
{
    float3 mono = lerp(gray, tint, 0.35) * float3(0.95, 1.05, 0.98);
    float3 ramp = (g * g) * float3(1.568628, 2.000000, 0.619608)
                + (g + 0.1) * float3(0.298039, 0.450980, 0.070588);
#if !NV_ALL_MODES
    /* Only the ordinary goggles change; headgear with a look of its own keeps
     * it, which is exactly the engine's modes 1 and 2. */
    if (mode == 1) return mono;
    if (mode == 2) return ramp;
#else
    /* Every mode, so the look stops depending on what is equipped. `mode` is
     * simply not consulted here, and drops out of the shader with it - HLSL
     * has no (void) cast, so an unused parameter is left as one. */
#endif
#if NV_DEFAULT_MODE == 1
    return mono;
#elif NV_DEFAULT_MODE == 2
    return ramp;
#elif NV_DEFAULT_MODE == 1
    return LookBLACK_AND_WHITE(g, NV_G_WHITE);
#elif NV_DEFAULT_MODE == 2
    return LookYELLOW_GREEN(g, NV_G_WHITE);
#elif NV_DEFAULT_MODE == 3
    return LookSEPIA(g, NV_G_WHITE);
#elif NV_DEFAULT_MODE == 4
    return LookAPOLLO(g, NV_G_WHITE);
#elif NV_DEFAULT_MODE == 5
    return LookLIGHTHOUSE(g, NV_G_WHITE);
#elif NV_DEFAULT_MODE == 6
    return LookTENNESSEE(g, NV_G_WHITE);
#elif NV_DEFAULT_MODE == 7
    return LookARLINGTON(g, NV_G_WHITE);
#elif NV_DEFAULT_MODE == 8
    return LookBRIDGE(g, NV_G_WHITE);
#elif NV_DEFAULT_MODE == 9
    return LookMONTENEGRO(g, NV_G_WHITE);
#elif NV_DEFAULT_MODE == 10
    return LookCHIEF(g, NV_G_WHITE);
#elif NV_DEFAULT_MODE == 11
    return LookSONGBIRD(g, NV_G_WHITE);
#elif NV_DEFAULT_MODE == 12
    return LookMADRE(g, NV_G_WHITE);
#elif NV_DEFAULT_MODE == 13
    return LookBURNER(g, NV_G_WHITE);
#elif NV_DEFAULT_MODE == 14
    return LookNEUTRAL(g, NV_G_WHITE);
#elif NV_DEFAULT_MODE == 15
    return LookAMBER(g, NV_G_WHITE);
#elif NV_DEFAULT_MODE == 16
    return LookCOOLBLUE(g, NV_G_WHITE);
#elif NV_DEFAULT_MODE == 17
    return LookCONTRAST(g, NV_G_WHITE);
#else
#error NV_DEFAULT_MODE names no look this build knows
#endif
}

#endif /* NV_LOOKS_HLSL */
